language: java

jdk:
  - oraclejdk8

env:
 ACTIVATOR_VERSION=1.3.2
- nvm install 0.10.33
- npm install -g grunt grunt-cli
- wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
- unzip -qo typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip

script:
- activator-${ACTIVATOR_VERSION}-minimal/activator clean compile
- activator-${ACTIVATOR_VERSION}-minimal/activator test
