language: java
jdk:
    - oraclejdk8

before_script:
- npm install -g grunt grunt-cli
- wget http://downloads.typesafe.com/typesafe-activator/1.3.12/typesafe-activator-1.3.12-minimal.zip
- unzip -qo typesafe-activator-1.3.12-minimal.zip

script:
- activator-1.3.12-minimal/activator clean compile
- activator-1.3.12-minimal/activator test